# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.7.0"

group :development do
  gem "bundler-audit", require: false
  gem "rspec"
  gem "rubocop"
  gem "rubocop-rspec", require: false
end
